spring:
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
#    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: ${REDIS_URL}
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
  #    org.hibernate.type: trace
cloud:
  aws:
    s3:
      bucket-origin: devstore-image-origin
      bucket-resizing: devstore-image-resized
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
# 스웨거 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tags-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui
  paths-to-match: /api/**

iamport:
  api-key: ${IAMPORT_API_KEY}
  secret-key: ${SECRET_KEY}
  merchant_uid: ${MERCHANT_UID}

mail:
  address:
    admin: ${ADMIN}
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    auth: true
    starttls:
      enable: true
  subject:
    user:
      registration: 가입 환영한다 얼간이들아
      active: 휴면계정 해제
  template:
    name:
      user:
        join: email-registration-member

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420
