name: deploy

on:
  pull_request:
    branches:
      - dev/FE
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo The PR was merged

      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./FE

      - name: Build CSS
        run: npm run buildcss
        working-directory: ./FE

      - name: Build
        run: npm run build
        working-directory: ./FE

      - name: SHOW AWS CLI VERSION
        run: |
          aws --version

      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 sync ./build s3://${{ secrets.DEV_AWS_S3_BUCKET }} --delete
        working-directory: ./FE
